"""``GeneratedCodeProbe`` (B4, S4-06) — marker-driven codegen detector.

Detects generated source files via two orthogonal signals:

1. **Header markers** (``_GENERATOR_HEADER_MARKERS``) — the canonical
   "this file was auto-generated by X" comment block emitted by every
   major Node-ecosystem codegen tool. First-marker-wins by tuple order
   (the tuple ordering IS the precedence policy).
2. **Well-known directory convention** (``_GENERATED_DIRS``) — files
   under conventional locations like ``src/generated/`` are flagged
   with ``generator: "directory_convention"`` even without a header.

``package.json#scripts`` is consulted to surface a ``regenerate_command``
when a matching script name is present (``codegen``, ``generate``,
``build:gql``, …). ``package.json#files`` is surfaced verbatim as
``build_outputs`` for the Phase-7 distroless build-stage decision.

The probe is **marker-based**: no parsing beyond ``read_bytes`` on
the first 4 KB of each candidate file. Phase 1's parser stack
(``parsers.safe_json``, ``parsers.jsonc``) covers anything richer.
The 100-LOC budget (AC-X1) keeps the discipline structural — a
contributor proposing to add a parsing pass is redirected to a
dedicated probe.

Sources:

- ``docs/phases/02-context-gather-layers-b-g/stories/S4-06-layer-b-marker-probes.md``
- ``docs/localv2.md §5.2 B4``
"""

from __future__ import annotations

import re
import time
from collections.abc import Iterator, Mapping
from pathlib import Path
from typing import Any, Final, Literal, TypeAlias

import structlog

from codegenie.errors import (
    DepthCapExceeded,
    MalformedJSONError,
    SizeCapExceeded,
    SymlinkRefusedError,
)
from codegenie.logging import EVENT_PROBE_START, EVENT_PROBE_SUCCESS
from codegenie.parsers import safe_json
from codegenie.probes.base import Probe, ProbeContext, ProbeOutput, RepoSnapshot, Task
from codegenie.probes.language_filter import _admits_node_project
from codegenie.probes.layer_b._indexable_files import _EXCLUDE_DIRS
from codegenie.probes.registry import register_probe

__all__ = ["GeneratedCodeProbe"]


_log = structlog.get_logger(__name__)


_WARNING_IDS: Final[frozenset[str]] = frozenset(
    {
        "generated_code.no_markers_detected",
        "generated_code.package_json_unparseable",
    }
)

_ID_PATTERN: Final[re.Pattern[str]] = re.compile(r"^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$")
for _id in _WARNING_IDS:
    if not _ID_PATTERN.match(_id):
        raise AssertionError(f"ADR-0007 violation: {_id!r}")


# Precedence is tuple order: first-marker-wins per file.
_GENERATOR_HEADER_MARKERS: Final[tuple[tuple[str, bytes], ...]] = (
    ("graphql-codegen", b"This file was automatically generated by graphql-codegen"),
    ("openapi-typescript", b"This file was auto-generated by openapi-typescript"),
    ("protoc-typescript", b"Code generated by protoc-gen-ts"),
    ("prisma", b"This file is auto-generated by Prisma"),
)
_BUILD_OUTPUT_DIRS: Final[frozenset[str]] = frozenset({"dist", "build", "out"})
_GENERATED_DIRS: Final[frozenset[str]] = frozenset({"src/generated", "__generated__", "gen"})
_MAX_HEAD_BYTES: Final[int] = 4096
_PKG_JSON_MAX_BYTES: Final[int] = 5 * 1024 * 1024
_SOURCE_SUFFIXES: Final[frozenset[str]] = frozenset({".ts", ".tsx", ".js", ".jsx"})
_REGEN_SCRIPT_KEYS_BY_GENERATOR: Final[Mapping[str, tuple[str, ...]]] = {
    "graphql-codegen": ("codegen", "build:gql", "graphql:codegen"),
    "openapi-typescript": ("generate:api", "codegen:api", "generate"),
    "protoc-typescript": ("generate:proto", "codegen:proto"),
    "prisma": ("prisma:generate", "generate"),
}

_Confidence: TypeAlias = Literal["high", "medium", "low"]


# ---------------------------------------------------------------------------
# Pure helpers (functional core — no I/O, no ctx)
# ---------------------------------------------------------------------------


def _detect_header_marker(content_head: bytes) -> str | None:
    """Return the first marker name whose canonical bytes are present in
    *content_head*. Precedence is the tuple iteration order."""
    for name, needle in _GENERATOR_HEADER_MARKERS:
        if needle in content_head:
            return name
    return None


def _detect_directory_marker(rel_path: str) -> bool:
    """Return True if *rel_path* sits under any well-known generated dir."""
    return any(rel_path == d or rel_path.startswith(f"{d}/") for d in _GENERATED_DIRS)


def _match_regenerate_command(generator: str, scripts: Mapping[str, Any]) -> str | None:
    """Return ``pnpm run <script>`` for the first matching script key for
    *generator*; ``None`` when no script name matches."""
    candidates = _REGEN_SCRIPT_KEYS_BY_GENERATOR.get(generator, ())
    for key in candidates:
        if key in scripts:
            return f"pnpm run {key}"
    return None


def _select_build_outputs(pkg: Mapping[str, Any] | None) -> list[str]:
    """Return ``package.json#files`` when it is a list of strings; else []."""
    if pkg is None:
        return []
    files = pkg.get("files")
    if not isinstance(files, list):
        return []
    return [str(f) for f in files if isinstance(f, str)]


def _walk_source_files(root: Path) -> Iterator[Path]:
    """Yield every ``.ts``/``.tsx``/``.js``/``.jsx`` file under *root*,
    excluding the canonical exclude dirs. Sorted for determinism."""
    matches: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file() or path.suffix not in _SOURCE_SUFFIXES:
            continue
        try:
            rel = path.relative_to(root)
        except ValueError:
            continue
        if any(part in _EXCLUDE_DIRS for part in rel.parts):
            continue
        matches.append(path)
    matches.sort(key=lambda p: p.as_posix())
    yield from matches


# ---------------------------------------------------------------------------
# Probe class (imperative shell)
# ---------------------------------------------------------------------------


@register_probe
class GeneratedCodeProbe(Probe):
    """Layer B — codegen-output marker probe (light heaviness)."""

    name: str = "generated_code"
    version: str = "0.1.0"
    layer = "B"
    tier = "base"
    applies_to_languages: list[str] = ["javascript", "typescript"]
    applies_to_tasks: list[str] = ["*"]
    requires: list[str] = ["language_detection"]
    timeout_seconds: int = 30
    cache_strategy: Literal["content"] = "content"
    declared_inputs: list[str] = [
        "**/*.ts",
        "**/*.tsx",
        "**/*.js",
        "package.json",
        "openapi.yaml",
        "openapi.yml",
        "schema.graphql",
        "prisma/schema.prisma",
    ]

    def applies(self, repo: RepoSnapshot, task: Task) -> bool:
        return _admits_node_project(self.applies_to_languages, repo.detected_languages, repo.root)

    async def run(self, repo: RepoSnapshot, ctx: ProbeContext) -> ProbeOutput:
        _log.info(EVENT_PROBE_START, probe=self.name)
        t0 = time.perf_counter()
        warnings: list[str] = []
        pkg_path = repo.root / "package.json"
        pkg = self._read_package_json(pkg_path, ctx, warnings)
        scripts_map = pkg.get("scripts", {}) if pkg else {}
        scripts: Mapping[str, Any] = scripts_map if isinstance(scripts_map, dict) else {}

        files_by_path: dict[str, dict[str, Any]] = {}
        for path in _walk_source_files(repo.root):
            rel = path.relative_to(repo.root).as_posix()
            try:
                head = path.read_bytes()[:_MAX_HEAD_BYTES]
            except OSError:
                continue
            generator = _detect_header_marker(head)
            if generator is not None:
                entry: dict[str, Any] = {"path": rel, "generator": generator}
                regen = _match_regenerate_command(generator, scripts)
                if regen is not None:
                    entry["regenerate_command"] = regen
                files_by_path[rel] = entry
            elif _detect_directory_marker(rel):
                files_by_path.setdefault(rel, {"path": rel, "generator": "directory_convention"})

        sorted_files = [files_by_path[k] for k in sorted(files_by_path)]
        build_outputs = sorted(set(_select_build_outputs(pkg)))
        confidence: _Confidence = "high" if sorted_files else "medium"
        if not sorted_files:
            warnings.append("generated_code.no_markers_detected")

        duration_ms = max(0, int((time.perf_counter() - t0) * 1000))
        _log.info(EVENT_PROBE_SUCCESS, probe=self.name, files=len(sorted_files))
        return ProbeOutput(
            schema_slice={
                "generated_code": {
                    "files": sorted_files,
                    "build_outputs": build_outputs,
                    "confidence": confidence,
                }
            },
            raw_artifacts=[],
            confidence=confidence,
            duration_ms=duration_ms,
            warnings=sorted(set(warnings)),
            errors=[],
        )

    def _read_package_json(
        self,
        pkg_path: Path,
        ctx: ProbeContext,
        warnings: list[str],
    ) -> Mapping[str, Any] | None:
        if not pkg_path.is_file():
            return None
        try:
            if ctx.parsed_manifest is not None:
                return ctx.parsed_manifest(pkg_path)
            return safe_json.load(pkg_path, max_bytes=_PKG_JSON_MAX_BYTES)
        except (MalformedJSONError, SizeCapExceeded, DepthCapExceeded, SymlinkRefusedError):
            warnings.append("generated_code.package_json_unparseable")
            return None
