"""Loader fixtures for ``tests/unit/plugins/test_loader.py``.

Helpers build synthetic plugin trees under a caller-supplied ``tmp_path``
without touching the production :mod:`codegenie.plugins` modules; the
loader is what's under test.

Every helper returns paths the test can hand straight to
:func:`codegenie.plugins.loader.load_plugins` or to
:func:`codegenie.plugins.loader.compute_plugin_tree_digest`.

Phase 3 plugin id convention: ``<task-class>--<language>--<build-system>``
(per :func:`codegenie.types.parsers.parse_plugin_id`'s grammar) — the
``"example--noop--npm"`` slug satisfies the regex while staying clearly
synthetic.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Final

__all__ = [
    "DEFAULT_SLUG",
    "MINIMAL_API_PY",
    "MINIMAL_MANIFEST_YAML",
    "make_fake_plugin_dir",
    "write_lockfile",
]


DEFAULT_SLUG: Final[str] = "example--noop--npm"

MINIMAL_MANIFEST_YAML: Final[str] = """\
name: {slug}
version: 0.1.0
scope:
  task_class: vulnerability-remediation
  languages: javascript
  build_systems: npm
contributes: {{}}
"""

# Default api.py body — empty side-effect module. Tests that need to
# observe a particular import side effect pass a custom ``api_body``.
MINIMAL_API_PY: Final[str] = "# autogenerated by tests/fixtures/plugins/loader_fixtures.py\n"


def make_fake_plugin_dir(
    plugin_root: Path,
    *,
    slug: str = DEFAULT_SLUG,
    manifest_body: str | None = None,
    api_body: str | None = MINIMAL_API_PY,
    include_manifest: bool = True,
) -> Path:
    """Create ``plugin_root/<slug>/`` with a manifest + optional ``api.py``.

    Returns the slug directory. Test code is responsible for computing the
    digest *after* building the tree (so the lockfile attests the final
    bytes) and for writing the lockfile via :func:`write_lockfile`.

    ``include_manifest=False`` produces a slug directory with no
    ``plugin.yaml`` — used by ``test_missing_manifest_returns_err``.
    ``api_body=None`` omits the ``api.py`` — used by
    ``test_import_error_returns_err`` (with a custom ``api_body``) and any
    test where the import side effect is irrelevant.
    """
    slug_dir = plugin_root / slug
    slug_dir.mkdir(parents=True, exist_ok=True)
    if include_manifest:
        manifest_text = (
            manifest_body if manifest_body is not None else MINIMAL_MANIFEST_YAML.format(slug=slug)
        )
        (slug_dir / "plugin.yaml").write_text(manifest_text, encoding="utf-8")
    if api_body is not None:
        (slug_dir / "api.py").write_text(api_body, encoding="utf-8")
    return slug_dir


def write_lockfile(plugin_root: Path, entries: dict[str, str]) -> Path:
    """Write ``plugin_root/PLUGINS.lock`` with the given ``{slug: digest}`` map.

    Returns the lockfile path; the caller passes it straight to
    :func:`codegenie.plugins.loader.load_plugins`.
    """
    lock_path = plugin_root / "PLUGINS.lock"
    lock_path.write_text(json.dumps(entries), encoding="utf-8")
    return lock_path
