"""Unit tests for ``codegenie.probes._lockfiles._yarn``.

Each test is keyed to an AC in S3-03 and names the mutation it catches in
its docstring (mutation-resistance per Rule 9 — tests verify intent).
"""

from __future__ import annotations

import importlib
import importlib.util
import inspect
import os
from pathlib import Path
from typing import Any

import pytest

from codegenie.errors import (
    MalformedLockfileError,
    SizeCapExceeded,
    SymlinkRefusedError,
)
from codegenie.probes._lockfiles import _yarn

YARN_LOCK_MINIMAL = """\
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


bcrypt@^5.1.0:
  version "5.1.1"
  resolved "https://registry.yarnpkg.com/bcrypt/-/bcrypt-5.1.1.tgz"
  integrity sha512-AGBHOG5...
  dependencies:
    node-addon-api "^5.0.0"
"""


# --- AC-2 — module surface ----------------------------------------------------


def test_module_all_exports_yarnlock_and_parse_only() -> None:
    """AC-2. Mutation caught: a future export leak (re-exporting a private
    helper or the module constants) would silently widen the public surface."""
    assert set(_yarn.__all__) == {"YarnLock", "YarnLockEntry", "parse"}


# --- AC-3 — module constants typed Final at the documented values -------------


def test_module_constants_are_final_with_documented_values() -> None:
    """AC-3. Mutation caught: silently changing the size cap or the
    parser_kind discriminator (both are pinned by arch §"Component design"
    #9 and the registry-pattern contract in ``parsers/_io.py``)."""
    assert _yarn.YARN_LOCKFILE_MAX_BYTES == 50 * 1024 * 1024
    assert _yarn._PARSER_KIND == "yarn_lockfile"


def test_parse_invokes_open_capped_with_module_constants(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """AC-3. Mutation caught: hard-coding alternate cap literals at the
    call site would make the module constants drift unnoticed; passing a
    different ``parser_kind`` would defeat the registry-pattern's payoff."""
    monkeypatch.setattr(_yarn, "_HAS_PYARN", False)
    lockfile = tmp_path / "yarn.lock"
    lockfile.write_text(YARN_LOCK_MINIMAL)
    captured: dict[str, Any] = {}

    def fake_open_capped(path: Path, *, max_bytes: int, parser_kind: str) -> bytes:
        captured["path"] = path
        captured["max_bytes"] = max_bytes
        captured["parser_kind"] = parser_kind
        return YARN_LOCK_MINIMAL.encode("utf-8")

    monkeypatch.setattr(_yarn, "open_capped", fake_open_capped)
    _yarn.parse(lockfile)
    assert captured["path"] == lockfile
    assert captured["max_bytes"] == _yarn.YARN_LOCKFILE_MAX_BYTES
    assert captured["parser_kind"] == "yarn_lockfile"


# --- AC-2, AC-11, AC-20 — happy path on the hand-rolled path -----------------


def test_parse_happy_path_handrolled_yields_entries(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """AC-11, AC-20. Force the hand-rolled path so the assertion is
    deterministic regardless of pyarn install state.

    Mutation caught: state-machine never enters in_entry_body (entries
    dict stays empty); ValueError("no yarn.lock entries parsed") raised
    instead of returning shaped dict.
    """
    monkeypatch.setattr(_yarn, "_HAS_PYARN", False)
    lockfile = tmp_path / "yarn.lock"
    lockfile.write_text(YARN_LOCK_MINIMAL)
    result = _yarn.parse(lockfile)
    assert "bcrypt@^5.1.0" in result["entries"]
    assert result["entries"]["bcrypt@^5.1.0"]["version"] == "5.1.1"
    assert (
        result["entries"]["bcrypt@^5.1.0"]["resolved"]
        == "https://registry.yarnpkg.com/bcrypt/-/bcrypt-5.1.1.tgz"
    )
    assert result["entries"]["bcrypt@^5.1.0"]["dependencies"] == {"node-addon-api": "^5.0.0"}


def test_parse_handrolled_total_false_admits_missing_integrity(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """AC-11. Mutation caught: ``total=True`` on YarnLockEntry would
    require ``integrity`` on every entry; yarn classic ≤ v1.21 omitted
    integrity hashes — the parser must not default them. The runtime
    assertion is the lookup; the load-bearing check is mypy --strict."""
    monkeypatch.setattr(_yarn, "_HAS_PYARN", False)
    body = (
        "# yarn lockfile v1\n\n"
        "lodash@^4.17.0:\n"
        '  version "4.17.21"\n'
        '  resolved "https://example.invalid/lodash-4.17.21.tgz"\n'
    )
    lockfile = tmp_path / "yarn.lock"
    lockfile.write_text(body)
    result = _yarn.parse(lockfile)
    assert "integrity" not in result["entries"]["lodash@^4.17.0"]
    assert result["entries"]["lodash@^4.17.0"]["version"] == "4.17.21"


# --- AC-6 — size cap (re-raised unchanged from open_capped) -------------------


def test_parse_oversized_file_reraises_size_cap(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """AC-6. Mutation caught: swallowing SizeCapExceeded into
    MalformedLockfileError (broad ``except Exception`` instead of the
    explicit passthrough). Uses ``os.fstat`` monkey-patch instead of
    writing 60 MB to tmpfs (Rule 2 — smallest test that proves the
    contract)."""
    lockfile = tmp_path / "yarn.lock"
    lockfile.write_text(YARN_LOCK_MINIMAL)

    real_fstat = os.fstat

    class FakeStat:
        def __init__(self, st: os.stat_result) -> None:
            self._st = st
            self.st_size = 60 * 1024 * 1024
            self.st_mode = st.st_mode

    def fake_fstat(fd: int) -> Any:
        return FakeStat(real_fstat(fd))

    monkeypatch.setattr(os, "fstat", fake_fstat)
    with pytest.raises(SizeCapExceeded):
        _yarn.parse(lockfile)


# --- AC-6 — symlink refusal (re-raised unchanged from open_capped) ------------


def test_parse_symlink_at_final_component_reraises_symlink_refused(
    tmp_path: Path,
) -> None:
    """AC-6. Mutation caught: any path that catches SymlinkRefusedError
    in the dispatch try/except and re-wraps it as MalformedLockfileError.
    The wrapper inherits open_capped's defense and must let the exception
    propagate unchanged."""
    real = tmp_path / "real.lock"
    real.write_text(YARN_LOCK_MINIMAL)
    link = tmp_path / "yarn.lock"
    link.symlink_to(real)
    with pytest.raises(SymlinkRefusedError):
        _yarn.parse(link)


# --- AC-7, AC-9, AC-10, AC-20 — malformed-bytes translation -------------------


def test_parse_malformed_bytes_handrolled_translates_to_malformed_lockfile(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """AC-7, AC-9. Mutation caught: dropping ``from cause`` (loses
    ``__cause__``); catching ``BaseException`` (would absorb
    KeyboardInterrupt); translating to a different marker class.
    Hand-rolled path is deterministic — pyarn's parse-error behavior is
    its own contract, not ours."""
    monkeypatch.setattr(_yarn, "_HAS_PYARN", False)
    lockfile = tmp_path / "yarn.lock"
    lockfile.write_text("malformed garbage with no entry header structure\n@@@@@\n")
    with pytest.raises(MalformedLockfileError) as exc:
        _yarn.parse(lockfile)
    # AC-9: __cause__ is some real exception (ValueError from the scanner).
    assert exc.value.__cause__ is not None
    # The cause's type name surfaces in the message for observability.
    assert type(exc.value.__cause__).__name__ in exc.value.args[0]


def test_parse_malformed_bytes_message_contains_path(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """AC-10. Mutation caught: building the message without the path
    (e.g., ``MalformedLockfileError(str(cause))``) — downstream WarningId
    construction in NodeManifestProbe recovers the path from
    ``args[0]``."""
    monkeypatch.setattr(_yarn, "_HAS_PYARN", False)
    lockfile = tmp_path / "yarn.lock"
    lockfile.write_text("not a yarn lockfile at all\n@@@\n")
    with pytest.raises(MalformedLockfileError) as exc:
        _yarn.parse(lockfile)
    assert str(lockfile) in exc.value.args[0]


def test_parse_invalid_utf8_handrolled_translates_to_malformed_lockfile(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """AC-7. Mutation caught: ``body.decode("utf-8", errors="replace")``
    would silently substitute the lossy character (U+FFFD) and the parser
    would attempt to scan garbage — surfacing a confusing ValueError far
    from the real cause. Strict decode means UnicodeDecodeError surfaces
    directly and is translated cleanly."""
    monkeypatch.setattr(_yarn, "_HAS_PYARN", False)
    lockfile = tmp_path / "yarn.lock"
    lockfile.write_bytes(b"# yarn lockfile v1\n\n\xff\xfe\xfd: invalid utf8 header\n")
    with pytest.raises(MalformedLockfileError) as exc:
        _yarn.parse(lockfile)
    assert isinstance(exc.value.__cause__, (UnicodeDecodeError, ValueError))


# --- AC-4 — _HAS_PYARN semantics ---------------------------------------------


def test_has_pyarn_reflects_find_spec_true(monkeypatch: pytest.MonkeyPatch) -> None:
    """AC-4. Mutation caught: probing pyarn via ``try: import pyarn``
    would (a) import the module unconditionally, defeating the no-import
    branch, and (b) catch errors other than ImportError. The probe must
    be ``importlib.util.find_spec``."""
    real_find_spec = importlib.util.find_spec

    def fake_find_spec(name: str, *args: Any, **kwargs: Any) -> Any:
        if name == "pyarn":
            return object()  # truthy non-None ModuleSpec stand-in
        return real_find_spec(name, *args, **kwargs)

    monkeypatch.setattr(importlib.util, "find_spec", fake_find_spec)
    reloaded = importlib.reload(_yarn)
    try:
        assert reloaded._HAS_PYARN is True
    finally:
        # Restore module state for sibling tests.
        importlib.reload(_yarn)


def test_has_pyarn_reflects_find_spec_false(monkeypatch: pytest.MonkeyPatch) -> None:
    """AC-4. Mutation caught: a hard-coded ``_HAS_PYARN = True`` (or
    False) would pass every other test depending on local install state.
    find_spec returning None must drive the flag."""
    real_find_spec = importlib.util.find_spec

    def fake_find_spec(name: str, *args: Any, **kwargs: Any) -> Any:
        if name == "pyarn":
            return None
        return real_find_spec(name, *args, **kwargs)

    monkeypatch.setattr(importlib.util, "find_spec", fake_find_spec)
    reloaded = importlib.reload(_yarn)
    try:
        assert reloaded._HAS_PYARN is False
    finally:
        importlib.reload(_yarn)


# --- AC-8, AC-21 — marker discipline -----------------------------------------


def test_raised_marker_has_no_instance_attributes(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """AC-8, AC-21. Mutation caught: a future "convenience" override of
    ``MalformedLockfileError.__init__(self, *, path, cause)`` would be
    flagged immediately. The Phase-0 invariant
    ``test_subclasses_are_markers_only`` guards the class-level contract;
    this test guards the construction site in _yarn.py."""
    monkeypatch.setattr(_yarn, "_HAS_PYARN", False)
    lockfile = tmp_path / "yarn.lock"
    lockfile.write_text("@@@@@ not a yarn lock\n")
    with pytest.raises(MalformedLockfileError) as exc:
        _yarn.parse(lockfile)
    assert len(exc.value.args) == 1
    assert isinstance(exc.value.args[0], str)
    for forbidden in ("path", "cap", "detail", "cause", "warning_id"):
        assert not hasattr(exc.value, forbidden), (
            f"MalformedLockfileError must remain a marker; instance must not "
            f"carry {forbidden!r}. Path lives in args[0]; cause lives on "
            f"__cause__."
        )


# --- AC-12 — no regex over full file -----------------------------------------


def test_yarn_module_does_not_run_regex_over_full_file() -> None:
    """AC-12. Mutation caught: a future "optimization" that replaces the
    line-by-line state machine with ``re.compile(...).findall(body)`` —
    that is the regex-DoS-prone shape this module is explicitly forbidden
    from adopting. Per-line bounded regex inside the loop is allowed (the
    test scans for module-scope ``re.compile`` and full-body
    ``re.search``/``re.findall``/``re.match`` patterns).

    Conservative — false positives are acceptable; false negatives (a
    real DoS-prone pattern slipping through) are not.
    """
    src = inspect.getsource(_yarn)
    assert "import re" not in src, (
        "_yarn.py must not import ``re``; the hand-rolled scanner is a "
        "state machine, not a regex. Adversarial regex-DoS lands in S5-02."
    )


# --- AC-17 — extension-by-addition (architectural test) ----------------------


def test_yarn_module_does_not_reference_sibling_parsers() -> None:
    """AC-17, CLAUDE.md "Extension by addition". Mutation caught: a
    future edit that imports ``_pnpm`` / ``_npm`` / ``_bun`` into
    ``_yarn`` — sibling parsers must be free to evolve independently.
    The shared kernels are ``parsers/_io.open_capped`` +
    ``codegenie.errors``, not other sibling modules."""
    src = inspect.getsource(_yarn)
    for forbidden in ("_pnpm", "_npm", "_bun"):
        assert forbidden not in src, (
            f"_yarn.py must not reference sibling parser {forbidden!r}; "
            f"adding a new lockfile format is a new file, not an edit here."
        )


# --- AC-1 — _lockfiles/__init__.py stays inert (S3-03 doesn't edit it) -------


def test_lockfiles_init_remains_inert() -> None:
    """AC-1, CLAUDE.md "Extension by addition". S3-01 settled the
    family-__init__ as inert; S3-02 reinforced; S3-03 must not touch it.
    The contract: ``__all__: list[str] = []`` and sibling parsers export
    from their own modules."""
    from codegenie.probes import _lockfiles

    assert getattr(_lockfiles, "__all__", None) == [], (
        "_lockfiles/__init__.py is settled as inert by S3-01 — S3-03 must "
        "not re-export YarnLock through it. Consumers import siblings "
        "directly."
    )
    for forbidden in ("PnpmLock", "NpmLock", "YarnLock", "YarnLockEntry"):
        assert not hasattr(_lockfiles, forbidden), (
            f"{forbidden} must be imported from its sibling module, not the "
            f"package __init__. Phase 2 may revisit if extracting a shared "
            f"helper into the package (rule of three)."
        )


# --- AC-18 — parser_kind discriminator surfaces on cap-exceeded event --------


def test_parser_kind_yarn_lockfile_surfaces_on_size_cap_event(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """AC-18. Mutation caught: passing ``parser_kind="safe_yaml"`` or
    omitting it would defeat the registry-pattern's payoff — downstream
    observability can no longer attribute the cap violation to the
    yarn-lockfile parser specifically. Test asserts the literal surfaces
    on the structured event."""
    import structlog.testing

    from codegenie.logging import EVENT_PROBE_PARSER_CAP_EXCEEDED

    lockfile = tmp_path / "yarn.lock"
    lockfile.write_text(YARN_LOCK_MINIMAL)

    real_fstat = os.fstat

    class FakeStat:
        def __init__(self, st: os.stat_result) -> None:
            self._st = st
            self.st_size = 60 * 1024 * 1024
            self.st_mode = st.st_mode

    def fake_fstat(fd: int) -> Any:
        return FakeStat(real_fstat(fd))

    monkeypatch.setattr(os, "fstat", fake_fstat)
    with structlog.testing.capture_logs() as events:
        with pytest.raises(SizeCapExceeded):
            _yarn.parse(lockfile)
    cap_events = [e for e in events if e.get("event") == EVENT_PROBE_PARSER_CAP_EXCEEDED]
    assert any(e.get("parser_kind") == "yarn_lockfile" for e in cap_events), (
        f"Expected parser_kind='yarn_lockfile' on a "
        f"{EVENT_PROBE_PARSER_CAP_EXCEEDED!r} event; got {cap_events!r}"
    )


# --- AC-15 — ADR-0003 land-time selection block is filled --------------------


def test_adr_0003_land_time_selection_block_is_filled() -> None:
    """AC-15. Mutation caught: shipping S3-03 without filling in the
    "Implementer's land-time selection" block of ADR-0003 — the ADR-vs-
    reality drift failure mode named in High-level-impl.md §"Step 3" #3.
    Test greps for the dated header pattern."""
    import re as _re

    adr_path = (
        Path(__file__).resolve().parents[4]
        / "docs"
        / "phases"
        / "01-context-gather-layer-a-node"
        / "ADRs"
        / "0003-yarn-lock-parser-choice.md"
    )
    text = adr_path.read_text()
    # Header pattern: "### Implementer's land-time selection (YYYY-MM-DD): ..."
    pattern = _re.compile(
        r"^###\s+Implementer's land-time selection\s+\(\d{4}-\d{2}-\d{2}\)",
        _re.MULTILINE,
    )
    assert pattern.search(text), (
        "ADR-0003 must carry a dated 'Implementer's land-time selection' "
        "header — the ADR-vs-reality drift gate (High-level-impl.md §Step 3 "
        "Implementation-level risks #3)."
    )
    # Negative: the placeholder line must be gone.
    assert "_(To be filled in at Phase 1 implementation time.)_" not in text, (
        "ADR-0003 still carries the placeholder line; the land-time block must replace it (AC-15)."
    )
