"""Shape test for ``tests/fixtures/portfolio/stale-scip/`` (S7-02).

Consumes the shared shape-test kernel at
``tests/fixtures/_shape_test_kernel.py``. The kernel owns the
parametrized-test machinery; this consumer declares only its
``_FILE_SPECS`` + the pure content predicates.

The stale-scip fixture is special in that:
- It uses a fixture-local micro-git-repo (gitignored `.git/`,
  `.codegenie/`) regenerated by `regenerate.sh`. The closed-set check
  asserts only the committed bytes.
- `_seed/scip-index.scip` is a binary file (no LF check; ``parser=None``
  marker).
- Several content predicates grep the static `regenerate.sh` script
  bytes — these pin the load-bearing Risk-#3 invariants at the
  script-text level.

Implements AC-15..AC-22 + AC-28..AC-31 + AC-33 from S7-02.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from tests.fixtures._shape_test_kernel import (
    _FORBIDDEN_SUBPATHS,
    _FileSpec,
    assert_file_content_invariants,
    assert_file_exists,
    assert_file_line_endings,
    assert_file_parses,
    assert_no_forbidden_subpath,
    assert_readme_references_every_spec,
    assert_tree_is_closed_set,
)

_FIXTURE = Path(__file__).parent.parent / "fixtures" / "portfolio" / "stale-scip"


# --- Pure content predicates -------------------------------------------------


def _pkg_declares_typescript(pkg: dict[str, Any]) -> None:
    """AC-16 — package.json declares typescript devDep."""
    assert pkg.get("name") == "stale-scip-fixture"
    assert pkg.get("private") is True
    assert pkg.get("devDependencies", {}).get("typescript") == "^5.3.0", (
        f"package.json must declare typescript@^5.3.0 (the version used to build "
        f"_seed/scip-index.scip per the seed-build ritual); got "
        f"devDependencies={pkg.get('devDependencies')!r}"
    )


def _tsconfig_shape(ts: dict[str, Any]) -> None:
    """AC-16 — tsconfig.json is valid; emits to dist/ which is gitignored."""
    co = ts.get("compilerOptions", {})
    assert co.get("strict") is True
    assert co.get("outDir") == "dist"


def _a_ts_exports(raw_bytes: bytes) -> None:
    text = raw_bytes.decode("utf-8")
    assert "export function add" in text
    assert "export const ANSWER" in text


def _b_ts_imports_a(raw_bytes: bytes) -> None:
    text = raw_bytes.decode("utf-8")
    assert 'from "./a"' in text
    assert "export function plusAnswer" in text


def _c_ts_imports_b(raw_bytes: bytes) -> None:
    text = raw_bytes.decode("utf-8")
    assert 'from "./b"' in text
    assert "export function tripleAnswer" in text


def _d_ts_imports_c(raw_bytes: bytes) -> None:
    text = raw_bytes.decode("utf-8")
    assert 'from "./c"' in text
    assert "export function doubleTriple" in text


def _e_ts_imports_d(raw_bytes: bytes) -> None:
    text = raw_bytes.decode("utf-8")
    assert 'from "./d"' in text
    assert "export function entry" in text


def _main_ts_imports_e(raw_bytes: bytes) -> None:
    text = raw_bytes.decode("utf-8")
    assert 'from "./src/e"' in text


# --- Seed-template predicates (AC-19, AC-15) ---------------------------------


def _template_carries_parent_commit_placeholder(parsed_json: dict[str, Any]) -> None:
    """AC-19 — seed template's last_indexed_commit is the placeholder string.

    Mutation: a contributor "tidies up" the template by replacing the
    placeholder with the actual prior commit SHA at fixture-creation
    time → this predicate fails (and the regenerate.sh substitution
    would no-op silently).
    """
    assert parsed_json.get("last_indexed_commit") == "PARENT_COMMIT", (
        f"_seed/scip-slice.template.json must carry the placeholder string "
        f"'PARENT_COMMIT' as last_indexed_commit (substituted at regen runtime); "
        f"got {parsed_json.get('last_indexed_commit')!r}"
    )


def _seed_template_counters_match_source_tree(parsed_json: dict[str, Any]) -> None:
    """AC-15(c) — files_indexed == files_in_repo == count(src/*.ts + main.ts).

    Mutation: contributor grows the source tree without updating the
    seed template → ``IndexHealthProbe`` would surface ``CoverageGap``
    instead of ``CommitsBehind`` and the adversarial fails for the
    wrong reason.
    """
    src_count = sum(1 for _ in (_FIXTURE / "src").glob("*.ts"))
    main_count = 1 if (_FIXTURE / "main.ts").exists() else 0
    total = src_count + main_count
    assert parsed_json.get("files_indexed") == total, (
        f"_seed/scip-slice.template.json files_indexed must equal "
        f"count(src/*.ts + main.ts) = {total}; got {parsed_json.get('files_indexed')!r}"
    )
    assert parsed_json.get("files_in_repo") == total, (
        f"_seed/scip-slice.template.json files_in_repo must equal "
        f"count(src/*.ts + main.ts) = {total}; got {parsed_json.get('files_in_repo')!r}"
    )


# --- SCIP binary predicates (AC-17) -------------------------------------------


def _scip_blob_non_empty(raw_bytes: bytes) -> None:
    """AC-17 — real binary SCIP blob, not the empty placeholder."""
    assert len(raw_bytes) > 0, (
        "_seed/scip-index.scip must be a real binary SCIP blob produced by "
        "scip-typescript per the seed-build ritual in README.md; the empty "
        "placeholder is the load-bearing thing S7-02 replaces."
    )


def _scip_blob_smoke_shape(raw_bytes: bytes) -> None:
    """AC-17 — binary passes a minimum-size sanity check (≥ 200 bytes).

    The placeholder was 0 bytes; any real ``scip-typescript`` output for
    a non-trivial source tree exceeds 200 bytes. NOT a deep structural
    assertion — the wire format is protobuf-serialized; consumers (S4-03)
    parse it.
    """
    assert len(raw_bytes) >= 200, (
        f"_seed/scip-index.scip is {len(raw_bytes)} bytes — below the 200-byte "
        f"sanity threshold. Either the seed-build ritual didn't run or the "
        f"scratch tree was empty."
    )


# --- regenerate.sh grep predicates (AC-18, AC-20, AC-21b, AC-31) -------------


def _regen_initializes_git_and_commits_two_commits(raw_bytes: bytes) -> None:
    text = raw_bytes.decode("utf-8")
    assert "rm -rf .git .codegenie" in text
    assert "git init -q -b main" in text
    assert "v0 — seeded last_indexed_commit" in text
    assert "v1 — HEAD moves forward" in text


def _regen_substitutes_parent_commit_into_template(raw_bytes: bytes) -> None:
    """AC-21b — regen substitutes PARENT_COMMIT into the template."""
    text = raw_bytes.decode("utf-8")
    assert "s|PARENT_COMMIT|" in text, (
        "regenerate.sh must substitute PARENT_COMMIT into "
        "_seed/scip-slice.template.json via sed; a contributor 'tidying up' "
        "by hardcoding the materialized scip.json would break this."
    )
    assert "_seed/scip-slice.template.json" in text
    assert ".codegenie/context/raw/scip.json" in text


def _regen_copies_seed_scip_to_runtime_path(raw_bytes: bytes) -> None:
    """AC-21b — regen copies the seed binary to .codegenie/."""
    text = raw_bytes.decode("utf-8")
    assert "cp _seed/scip-index.scip .codegenie/context/raw/scip-index.scip" in text, (
        "regenerate.sh must copy _seed/scip-index.scip (the committed seed bytes) "
        "to .codegenie/context/raw/scip-index.scip — NOT invoke scip-typescript "
        "at regen time (the seed-build ritual is OUT-OF-BAND per ADR-0001)."
    )


def _last_indexed_defaults_to_head_tilde_one(raw_bytes: bytes) -> None:
    """AC-20 — LAST_INDEXED defaults to HEAD~1 (the parent), never HEAD.

    Mutation: a contributor "fixes" regenerate.sh to default LAST_INDEXED
    to HEAD → this predicate fails AND the adversarial fails (the
    materialized scip.json carries last_indexed == HEAD).
    """
    text = raw_bytes.decode("utf-8")
    assert 'LAST_INDEXED="${LAST_INDEXED:-$(git rev-parse HEAD~1)}"' in text, (
        "regenerate.sh must default LAST_INDEXED to HEAD~1 (the parent), "
        "NEVER HEAD itself. This is the Risk-#3 front-line guard."
    )


def _regen_refuses_current_head(raw_bytes: bytes) -> None:
    """AC-20 — explicit guard against operator-forced LAST_INDEXED=HEAD."""
    text = raw_bytes.decode("utf-8")
    assert '[[ "$LAST_INDEXED" == "$(git rev-parse HEAD)" ]]' in text, (
        "regenerate.sh must contain an explicit check against operator-forced "
        "LAST_INDEXED=$(git rev-parse HEAD). This is the second Risk-#3 layer."
    )
    assert "exit 1" in text
    assert "refuses to set last_indexed_commit" in text


def _regen_invokes_only_allowlisted_binaries(raw_bytes: bytes) -> None:
    """AC-31 — the regen script's invoked binaries are git + coreutils only.

    The tokenizer-based test in
    ``test_fixture_stale_scip_regenerate_allowlist.py`` is the
    authoritative check; this content predicate is a textual smoke that
    `scip-typescript` and `pnpm` strings don't appear at line-start
    (they could appear in comments — that's fine).
    """
    text = raw_bytes.decode("utf-8")
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        # No regen-time invocation of scip-typescript or pnpm.
        assert not stripped.startswith("scip-typescript "), (
            f"regenerate.sh invokes scip-typescript at line-start: {line!r}. "
            "The seed-build ritual is OUT-OF-BAND."
        )
        assert not stripped.startswith("pnpm "), (
            f"regenerate.sh invokes pnpm at line-start: {line!r}. "
            "pnpm is NOT in ALLOWED_BINARIES per ADR-0001."
        )


# --- README predicates (AC-22) -----------------------------------------------


def _readme_documents_structural_assertion(raw_bytes: bytes) -> None:
    """AC-22 — README pins the structural-assertion phrasing verbatim."""
    text = raw_bytes.decode("utf-8")
    assert "CommitsBehind.n >= 1" in text
    assert "last_indexed != current_HEAD" in text


def _readme_documents_regen_ritual(raw_bytes: bytes) -> None:
    text = raw_bytes.decode("utf-8")
    assert "Regeneration" in text
    assert "regenerate.sh" in text


def _readme_documents_seed_build_ritual(raw_bytes: bytes) -> None:
    """AC-22 — README documents the OUT-OF-BAND seed-build ritual."""
    text = raw_bytes.decode("utf-8")
    assert "Seed-build ritual" in text, (
        "README.md must document the seed-build ritual (one-time per "
        "scip-typescript version bump; OUT-OF-BAND). This is the AC-21a "
        "documentation requirement."
    )


def _readme_pins_scip_typescript_version(raw_bytes: bytes) -> None:
    """AC-22 — README pins the scip-typescript version used for the seed."""
    text = raw_bytes.decode("utf-8")
    import re

    pinned = re.search(r"scip-typescript\s+v?\d+\.\d+\.\d+", text)
    assert pinned is not None, (
        "README.md must pin the scip-typescript version used to build "
        "_seed/scip-index.scip (regex: scip-typescript v?N.N.N). When the "
        "tool version updates, regen the seed binary and bump this pin."
    )


# --- .gitignore predicate (AC-17) --------------------------------------------


def _gitignore_excludes_git_and_codegenie(raw_bytes: bytes) -> None:
    """AC-17 — .gitignore lists .git/ AND .codegenie/ verbatim.

    No `.codegenie/` carve-out: the real seed binary lives at
    ``_seed/scip-index.scip``, NOT under `.codegenie/`. S7-01's central
    no-committed-cache guard rests on this.
    """
    text = raw_bytes.decode("utf-8")
    lines = {
        line.strip()
        for line in text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }
    assert ".git/" in lines, f".gitignore must list `.git/`; got non-comment lines {lines!r}"
    assert ".codegenie/" in lines, f".gitignore must list `.codegenie/`; got {lines!r}"


# --- The single source of truth (closed set; AC-28) --------------------------

_FILE_SPECS: tuple[_FileSpec, ...] = (
    _FileSpec(
        "package.json",
        ("node_build_system", "node_manifest"),
        "safe_json",
        (_pkg_declares_typescript,),
    ),
    _FileSpec("tsconfig.json", ("node_build_system",), "jsonc", (_tsconfig_shape,)),
    _FileSpec("src/a.ts", ("language_detection",), "text", (_a_ts_exports,)),
    _FileSpec("src/b.ts", ("language_detection",), "text", (_b_ts_imports_a,)),
    _FileSpec("src/c.ts", ("language_detection",), "text", (_c_ts_imports_b,)),
    _FileSpec("src/d.ts", ("language_detection",), "text", (_d_ts_imports_c,)),
    _FileSpec("src/e.ts", ("language_detection",), "text", (_e_ts_imports_d,)),
    _FileSpec("main.ts", ("language_detection",), "text", (_main_ts_imports_e,)),
    _FileSpec("CHANGELOG.md", (), "text", ()),
    _FileSpec(
        "_seed/scip-slice.template.json",
        ("scip_index", "index_health"),
        "safe_json",
        (_template_carries_parent_commit_placeholder, _seed_template_counters_match_source_tree),
    ),
    _FileSpec(
        "_seed/scip-index.scip",
        ("scip_index",),
        None,  # binary; opt out of LF check + parser-driven checks
        (_scip_blob_non_empty, _scip_blob_smoke_shape),
    ),
    _FileSpec(
        "regenerate.sh",
        (),
        "text",
        (
            _regen_initializes_git_and_commits_two_commits,
            _regen_substitutes_parent_commit_into_template,
            _regen_copies_seed_scip_to_runtime_path,
            _last_indexed_defaults_to_head_tilde_one,
            _regen_refuses_current_head,
            _regen_invokes_only_allowlisted_binaries,
        ),
    ),
    _FileSpec(
        "README.md",
        (),
        "text",
        (
            _readme_documents_structural_assertion,
            _readme_documents_regen_ritual,
            _readme_documents_seed_build_ritual,
            _readme_pins_scip_typescript_version,
        ),
    ),
    _FileSpec(".gitignore", (), "text", (_gitignore_excludes_git_and_codegenie,)),
    _FileSpec(".gitattributes", (), "text", ()),
)


# --- Parametrize wrappers (delegate to kernel helpers) -----------------------


def test_fixture_directory_exists() -> None:
    """AC-15 — fixture directory exists."""
    assert _FIXTURE.is_dir()


@pytest.mark.parametrize("spec", _FILE_SPECS, ids=lambda s: s.relpath)
def test_fixture_file_exists(spec: _FileSpec) -> None:
    assert_file_exists(_FIXTURE, spec)


@pytest.mark.parametrize("spec", _FILE_SPECS, ids=lambda s: s.relpath)
def test_fixture_file_parses(spec: _FileSpec) -> None:
    assert_file_parses(_FIXTURE, spec)


@pytest.mark.parametrize("spec", _FILE_SPECS, ids=lambda s: s.relpath)
def test_fixture_file_content_invariants(spec: _FileSpec) -> None:
    assert_file_content_invariants(_FIXTURE, spec)


@pytest.mark.parametrize("spec", _FILE_SPECS, ids=lambda s: s.relpath)
def test_fixture_file_line_endings(spec: _FileSpec) -> None:
    """LF-only; binary specs (parser=None) are exempt."""
    assert_file_line_endings(_FIXTURE, spec)


@pytest.mark.parametrize("forbidden", _FORBIDDEN_SUBPATHS)
def test_no_forbidden_subpaths(forbidden: str) -> None:
    """Forbidden subpaths absent (.codegenie/ is gitignored, regenerated)."""
    if forbidden == ".codegenie":
        # `.codegenie/` is regenerated by regenerate.sh — it MAY exist on
        # disk post-regen but is gitignored. The closed-set test via
        # `git ls-files` catches stray COMMITTED `.codegenie/` content.
        return
    assert_no_forbidden_subpath(_FIXTURE, forbidden)


def test_fixture_tree_is_closed_set() -> None:
    """AC-28 — tracked-files set == _FILE_SPECS relpath set.

    Gitignored `.git/` and `.codegenie/` do NOT appear in `git ls-files`
    output; the closed set is exactly the committed bytes.
    """
    assert_tree_is_closed_set(_FIXTURE, _FILE_SPECS)


def test_readme_references_every_spec() -> None:
    """README mentions every relpath + every consumer probe."""
    assert_readme_references_every_spec(_FIXTURE, _FILE_SPECS)
